beeteach/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("accounts/", include("allauth.urls")),
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path("", include("post.urls"), name="post-urls"),
]

post/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('resource_create/',
         views.resource_create, name='resource_create'),
    path('resource_list/',
         views.resource_list, name='resource_list'),
    path('user_posts_list/', views.user_posts_list,
         name='user_posts_list'),
    path('<slug:slug>/resource_preview',
         views.resource_preview, name='resource_preview'),
    path('<slug:slug>/delete_resource/',
         views.resource_delete, name='resource_delete'),
    path('<slug:slug>/resource_detail',
         views.resource_detail, name='resource_detail'),
    path('<slug:slug>/like/',
         views.like_resource, name='like_resource'),
    path('<slug:slug>/edit_comment/<int:comment_id>',
         views.comment_edit, name='comment_edit'),
    path('<slug:slug>/delete_comment/<int:comment_id>',
         views.comment_delete, name='comment_delete'),
    path('<slug:slug>/edit_resource/<int:resource_id>',
         views.resource_edit, name='resource_edit'),

    path('', views.home_page, name='home'),
]

post/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField

KEYSTAGE = ((0, "Early Years"), (1, "Key Stage 1"),
            (2, "Key Stage 2"), (3, "Key Stage 3"))
STATUS = ((0, "Draft"), (1, "Published"))

class Resource(models.Model):
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="resource_posts"
    )
    title = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=100, unique=True)
    key_stage = models.IntegerField(choices=KEYSTAGE, default=0)
    content = models.TextField(blank=True)
    links = models.TextField(blank=True)
    status = models.IntegerField(choices=STATUS, default=0)
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    # Sorts newest first, remove '-' to sort oldest first
    class Meta:
        ordering = ["-created_on"]

    # Represents self instance in admin panel
    def __str__(self):
        return f"{self.title} | written by {self.author}"


class Comment(models.Model):
    resource = models.ForeignKey(
        Resource, on_delete=models.CASCADE, related_name="comments"
    )
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="commenter"
    )
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["created_on"]

    def __str__(self):
        return f"Comment {self.body} by {self.author}"


class Like(models.Model):
    resource = models.ForeignKey(
        Resource, on_delete=models.CASCADE, related_name="likes"
    )
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="liker"
    )
    created_on = models.DateTimeField(auto_now_add=True)

    # Ensures that a user can only like a resource once
    class Meta:
        unique_together = ('resource', 'author')

    def __str__(self):
        return f'Like by {self.author} on {self.resource}'


class Media(models.Model):
    resource = models.ForeignKey(
        Resource, on_delete=models.CASCADE, related_name="media"
    )
    # This field can store either images or PDFs
    featured_media = CloudinaryField('image', default='placeholder')
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Media for {self.resource}'


class Feature(models.Model):
    resource = models.ForeignKey(
        Resource, on_delete=models.CASCADE,
        related_name="features", blank=True, null=True
    )
    title = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=100, unique=True)
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)

    # Sorts newest first, remove '-' to sort oldest first
    class Meta:
        ordering = ["-created_on"]

    # Represents self instance in admin panel
    def __str__(self):
        return f"{self.title}"

post/forms.py
from .models import Comment, Resource, Media
from django import forms
from django_summernote.widgets import SummernoteWidget


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)


class ResourceForm(forms.ModelForm):
    class Meta:
        model = Resource
        fields = ('title', 'key_stage', 'content', 'links', 'status',)


class MediaForm(forms.ModelForm):
    class Meta:
        model = Media
        fields = ('featured_media',)

    def clean_featured_media(self):
        media = self.cleaned_data.get('featured_media')

        if media and not media.content_type.startswith('image'):
            raise forms.ValidationError("Only image files are allowed.")

        return media

post/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404, redirect, reverse
from django.utils.text import slugify
from django.views import generic
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.db.models import Q
from .models import Resource, Media, Feature, Comment, Like
from .forms import CommentForm, ResourceForm, MediaForm


def home_page(request):
    """
    Displays the homepage with the most recently published resources

    **Context**

    ``resources``
        A queryset of the latest 4 :model:1post.Resource`
          published objects (status=1), ordered by creation date

    ``images``
        A queryset of :model:`post.Media` related to the 4 resources.

    *Template:*

    :template:`post/index.html`
    """

    queryset = Resource.objects.filter(status=1).order_by("-created_on")
    resources = queryset[:4]
    images = Media.objects.filter(resource__in=resources)

    return render(
        request,
        "post/index.html",
        {"resources": resources, "images": images}
    )


@login_required
def resource_list(request):
    """
    Displays the logged in homepage,
      showing a paginated list of published resources

    **Context**

    ``resources``
        A queryset of the :model:`post.Resource`
          published objects (status=1), ordered by creation date

    ``featured``
        A queryset of the :model:`post.Feature` objects

    ``page_obj``
        A paginated object containing a set of ``resources``
          dependent on the current page number

    *Template:*

    If a page_number is returned from the get function
      the partial template is rendered:

    :template:`post/partials/resource_list.html`

    Otherwise the full template is rendered:

    :template:`post/resource_list.html`
    """
    resources = Resource.objects.filter(status=1).order_by("-created_on")
    features = Feature.objects.all()

    pagination_amount = 5
    paginator = Paginator(resources, pagination_amount)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    if page_number:
        return render(request, 'post/partials/resource_list.html',
                      {'page_obj': page_obj})

    return render(
        request,
        "post/resource_list.html",
        {"page_obj": page_obj, "features": features},
    )


@login_required
def user_posts_list(request):
    """
    Displays a list of the logged-in user's posted :model:`post.Resource`
      titles with associated edit and delete buttons.

    **Context**

    ``user_resources``
        A queryset of :model:`post.Resource` objects,
        filtered by logged-in user (author=request.user).

    ``resource_form``
        An instance of :form:`post.ResourceForm`,
          used to edit an existing resource.

    **Template**

    :template:`post/user_posts_list.html`
    """

    if request.user.is_superuser:
        user_resources = Resource.objects.filter(Q(status=1) | Q(author=request.user))
    else:
        user_resources = Resource.objects.filter(author=request.user)

    resource_form = ResourceForm()

    return render(
        request,
        "post/user_posts_list.html",
        {
            "user_resources": user_resources,
            "resource_form": resource_form,
        },
    )


@login_required
def resource_detail(request, slug):
    """
    Display an individual :model:`post.Resource`
      with related media and comments.

    **Context**

    ``resource``
        An instance of :model:`post.Resource`, filtered by status and slug

    ``images``
        An queryset of :model:`post.Media` related to the resource

    ``comments``
        An queryset of :model:`post.Comments` related to the resource,
          ordered by creation date

    ``comment_count``
        An integer representing the total number of
        comments related to the resource.

    ``comment_form``
        An instance of :form:`post.CommentForm` for submitting a new comment.

    **POST behavior**

    If a valid POST request is made, a new comment is created,
      linked to the resource, and associated with the logged-in user.

    **Template:**

    :template:`post/resource_detail.html`
    """

    queryset = Resource.objects.filter(status=1)
    resource = get_object_or_404(queryset, slug=slug)
    images = Media.objects.filter(resource=resource.id)
    comments = resource.comments.all().order_by("-created_on")
    comment_count = comments.count()
    like_count = resource.likes.count()

    if request.method == "POST":
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.author = request.user
            comment.resource = resource
            comment.save()

            messages.success(request, "Comment Added")

    comment_form = CommentForm()

    return render(
        request,
        "post/resource_detail.html",
        {
            "resource": resource,
            "images": images,
            "comments": comments,
            "comment_count": comment_count,
            "comment_form": comment_form,
            "like_count": like_count,
        },
    )


@login_required
def resource_preview(request, slug):
    """
    Display an individual :model:`post.Resource` draft.

    **Context**

    ``resources``
        An instance of :model:`post.Resource`,
          filtered by the logged-in user and slug

    ``images``
        An queryset of :model:`post.Media` related to the resource

    **Template**

    :template:`post/resource_preview.html`
    """

    queryset = Resource.objects.filter(author=request.user)
    resource = get_object_or_404(queryset, slug=slug)
    images = Media.objects.filter(resource=resource.id)

    return render(
        request,
        "post/resource_preview.html",
        {
            "resource": resource,
            "images": images,
        },
    )


@login_required
def resource_create(request):
    """
    Handles the creation of a new :model:`post.Resource`
      and its associated media files.

    **Context**

    ``resource_form``
        An instance of :form:`post.ResourceForm`,
        used to create a new resource.

    ``media_form``
        An instance of :form:`post.MediaForm`,
          used to upload media files for the resource.

    **POST behavior**

    - The ``resource_form`` is validated.
    - If valid, the resource is saved with the logged-in user as the author.
    - If `Media` files are added, they are associated with
        the resource and saved.
    - A success message is displayed based on the resource status
        (published or draft), and the user is redirected to
        the appropriate page.

    **Template**

    :template:`post/resource_create.html`
    """

    if request.method == 'POST':
        resource_form = ResourceForm(request.POST)
        media_files = request.FILES.getlist('featured_media')

        if resource_form.is_valid():
            resource = resource_form.save(commit=False)
            resource.slug = slugify(resource.title)
            resource.author = request.user
            resource.save()

            for media_file in media_files:
                Media.objects.create(resource=resource,
                                     featured_media=media_file)

            if resource.status == 1:
                messages.success(request, "Resource Posted")
                return redirect('resource_detail', slug=resource.slug)
            else:
                messages.success(
                    request, "Resource Draft Created" +
                    " (Publish your resource from the 'My Resources' Page)")
                return redirect('resource_preview', slug=resource.slug)

    resource_form = ResourceForm()
    media_form = MediaForm()

    return render(
        request,
        "post/resource_create.html",
        {
            "resource_form": resource_form,
            "media_form": media_form,
        },
    )


@login_required
def resource_edit(request, slug, resource_id):
    """
    Handles the editing of an existing :model:`post.Resource`
      and its associated media files by the logged-in user.

    **Context**

    ``resource``
        An instance of :model:`post.Resource`, retrieved by its ID.

    ``media_files``
        A list of media files (images) uploaded to associate with the resource.

    ``resource_form``
        An instance of :form:`post.ResourceForm`,
          pre-filled with the existing resource data for editing.


    **POST behavior**
    - If valid, the resource is updated with the modified data.
    - If new media files are added, they are saved and
        associated with the resource.
    - A success message is displayed when the resource is successfully updated,
        and the user is redirected to the "My Resources" page.
    - If the form is invalid or the user is not the author,
        an error message is displayed.

    **Template**

    :template:`post/user_posts_list.html`
    """

    if request.method == "POST":

        resource = get_object_or_404(Resource, pk=resource_id)
        media_files = request.FILES.getlist('featured_media')

        if resource.author == request.user:
            resource_form = ResourceForm(data=request.POST, instance=resource)

        if resource_form.is_valid() and resource.author == request.user:
            resource = resource_form.save(commit=False)
            resource.slug = slugify(resource.title)
            resource.save()

            for media_file in media_files:
                Media.objects.create(resource=resource,
                                     featured_media=media_file)

            if resource.status == 1:
                messages.success(request, "Resource Posted")
                return redirect('resource_detail', slug=resource.slug)

post/templates/post/resource_create.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block meta %}
<meta name="description" content="Bee Teach, the educational community hive. Create a new educational resource.">
{% endblock %}

{% block content %}
<div class="container">
    <div class="row justify-content-center my-3">
        <div class="col col-md-10 col-lg-8 text-center">
            <h1>Create A Resource</h1>
            <p>To share your own resources, just choose a title, key stage and set the status to published.<br>
                You can also add text, upload images, and add a single link to your resource.<br>
                Once you have added all your details, simply hit "Submit" to upload your resource.<br>
                Don't forget to change the status to published if you want to post your resource straight away,<br>
                or leave the status as draft to edit before posting.
            </p>
        </div>
    </div>
    <div class="row justify-content-center my-3">
        <div class="col col-md-10 col-lg-8">
            <div class="card create-resource-card">
                {% if user.is_authenticated %}
                <div class="card-header slim-border">
                    <h4 class="text-center fs-2">New Resource</h4>
                    <p class="mb-0 d-flex justify-content-between"><span>Posting as: {{ user.username }}</span><span>*Required field</span></p>
                </div>
                <div class="card-body slim-border">
                    <form id="resourceForm" method="post" enctype="multipart/form-data">
                        {{ resource_form | crispy }}
                        <label for="id_featured_media">Upload Images</label>
                        <input type="file" name="featured_media" id="id_featured_media" multiple>
                        {% csrf_token %}
                        <button id="submitButton" type="submit" class="btn btn-lg">Submit</button>
                    </form>
                    {% else %}
                    <p>Log in to post a resource</p>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    <div class="row justify-content-center my-3">
        <div class="col col-md-10 col-lg-8 text-center">
            <p>
                Note: Only share resources you own or are free to use / public license.<br>
                <strong>DO NOT</strong> share paid for resources from other websites, books or alternative media.
            </p>
        </div>
    </div>
</div>
{% endblock %}

{% block script %}
<script>
    $(document).ready(function() {
        $('#id_content').summernote();
    });
</script>
{% endblock script %}

post/templates/post/resource_detail.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block meta %}
<meta name="description" content="Bee Teach, the educational community hive. Take a look at this free educational resource.">
{% endblock %}

{% block content %}
<div class="container">
    <div class="row justify-content-center my-5">
        <div class="col-11 col-md-10 col-xl-8">
            <div class="card detail-card my-3">
                <div class="card-header">
                    <h1 class="text-center my-1">{{ resource.title }}</h1>
                    <p id="key-stage" class="m-0 key-stage text-end fs-6">{{ resource.key_stage }}</p>
                    <p class="m-0 text-end fs-6">Shared by {{ resource.author }} on {{ resource.created_on }}</p>
                </div>
                <div class="card-body">
                    <article class="fs-5">
                        <h2 class="d-none">Article title: {{ resource.title }}</h2>
                        {{ resource.content | safe}}
                    </article>
                    <div id="carouselResourceDetail{{ resource.id }}" class="carousel slide card-carousel">
                        <div class="carousel-inner">
                            {% if resource.media.all %}
                                {% for media in resource.media.all %}
                                <div class="carousel-item {% if forloop.first %}active{% endif %}">
                                    <div class="card-img-box">
                                        <img src="{{ media.featured_media.url }}" class="resource-image d-block"
                                            alt="Image for {{ resource.title }}">
                                    </div>
                                    <div class="media-download text-center">
                                        <a href="{{ media.featured_media.url }}" download="{{ media.featured_media.name }}"
                                            class="btn my-2" target="_blank">Download Image</a>
                                    </div>
                                </div>
                                {% endfor %}
                            {% else %}
                                <div class="carousel-item active">
                                    <div class="card-img-box">
                                        <img src="{% static 'images/bee-heart.png' %}" class="resource-image d-block" alt="cartoon bee">
                                    </div>
                                </div>
                            {% endif %}
                        </div>
                        {% if resource.media.count > 1 %}
                            <button class="carousel-control-prev" type="button"
                                data-bs-target="#carouselResourceDetail{{ resource.id }}" data-bs-slide="prev">
                                <span class="carousel-control-prev-icon dark-bg" aria-hidden="true"></span>
                                <span class="visually-hidden">Previous</span>
                            </button>
                            <button class="carousel-control-next" type="button"
                                data-bs-target="#carouselResourceDetail{{ resource.id }}" data-bs-slide="next">
                                <span class="carousel-control-next-icon dark-bg" aria-hidden="true"></span>
                                <span class="visually-hidden">Next</span>
                            </button>
                        {% endif %}
                    </div>
                </div>
                {% if resource.links %}
                <div class="card-footer">
                    <div class="row">
                        <div class="col col-12 text-truncate text-center details-link">
                            Link -
                            <a href="{{ resource.links }}" target="_blank"
                                aria-label="link to external website, opens in a new page">
                                {{ resource.links }}
                            </a>
                        </div>
                    </div>
                </div>
                {% endif %}
            </div>
        </div>
    </div>

    <div class="row justify-content-center mb-5">
        <div class="col-11 col-md-10 col-xl-8">
            <div class="d-flex justify-content-between my-2">
                <h3 class="mx-3">Comments: {{ comment_count }}</h3>
                <div class="d-flex">
                    <h3>Likes: <span id="like-count{{ resource.id }}">{{ like_count }}</span></h3>
                    <form method="post" action="{% url 'like_resource' resource.slug %}" class="like-form">
                        {% csrf_token %}
                        <button type="submit" class="btn mx-3 like-btn">Like</button>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-11 col-md-10 col-xl-8">
            <div class="accordion accordion-flush rounded mb-3" id="commentAccordion">
                <div class="accordion-item rounded">
                  <h2 class="accordion-header">
                    <button class="accordion-button collapsed rounded d-md-flex justify-content-between" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseOne" aria-expanded="false" aria-controls="flush-collapseOne">
                        <span>Leave a comment <i class="fa-regular fa-comment"></i></span>
                        <small class="mb-0 ms-auto">Commenting as: {{ user.username }}</small>
                    </button>
                  </h2>
                  <div id="flush-collapseOne" class="accordion-collapse collapse" data-bs-parent="#commentAccordion">
                    <div class="accordion-body">
                        {% if user.is_authenticated %}
                            <form id="commentForm" method="post">
                                {{ comment_form | crispy }}
                                {% csrf_token %}
                                <button id="submitCommentButton" type="submit" class="btn btn-lg">Submit</button>
                            </form>
                        {% else %}
                        <p>Log in to leave a comment</p>
                        {% endif %}
                    </div>
                  </div>
                </div>
            </div>

            {% for comment in comments %}
            <div class="card comment-card mb-3">
                <div id="comment{{comment.id}}" class="card-body">
                    {{ comment.body | linebreaks }}
                </div>
                <div class="card-footer d-flex justify-content-between">
                    <p class="mb-0"><span class="fw-bold">{{ comment.author }}</span> - {{ comment.created_on }}</p>
                    <div>
                    {% if user.is_authenticated and comment.author == user %}
                        <button class="btn edit-button" data-comment_id="{{ comment.id }}">Edit</button>
                    {% elif user.is_authenticated and comment.author == user or user.is_superuser %}
                        <button type="button" class="btn" data-bs-toggle="modal" data-bs-target="#deleteCommentModal{{ comment.id }}"> Delete </button>
                    {% endif %}
                    </div>
                </div>
            </div>

            <div class="modal fade" id="deleteCommentModal{{ comment.id }}" tabindex="-1" aria-labelledby="deleteCommentModalLabel{{ comment.id }}" aria-hidden="true">
                <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                    <h1 class="modal-title fs-5" id="deleteCommentModalLabel{{ comment.id }}">Delete Comment?</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        Are you sure you want to delete your comment?
                    </div>
                    <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <a id="confirmCommentDelete{{ comment.id }}" href="{% url 'comment_delete' resource.slug comment.id %}" class="btn">Delete</a>
                    </div>
                </div>
                </div>
            </div>
            {% endfor %}

        </div>
    </div>
</div>
{% endblock content %}

{% block script %}
<script src="{% static 'js/script.js' %}"></script>
<script src="{% static 'js/comments.js' %}"></script>
<!-- Script to hide the django auto generated form label and add a placeholder to the textarea input -->
<script>
    document.querySelector('label[for="id_body"]').style.display = "none";
    document.getElementById("id_body").placeholder = "Enter Comment Here";
</script>
{% endblock %}

post/templates/post/resource_preview.html
{% extends 'base.html' %}

{% load static %}
{% load crispy_forms_tags %}

{% block meta %}
<meta name="description" content="Bee Teach, the educational community hive. A drafted resource.">
{% endblock %}

{% block content %}
<div class="container">
    <div class="row mt-5">
        <div class="col">
            <h1 class="text-center">Resource Draft</h1>
        </div>
    </div>

    <div class="row">
        <div class="col">
            <div class="card detail-card my-5">
                <div class="card-header">
                    <h1 class="text-center mb-2 mt-3">{{ resource.title }}</h1>
                    <p class="m-0 key-stage text-end fs-6">{{ resource.key_stage }}</p>
                    <p class="text-end fs-6">Shared by {{ resource.author }} on {{ resource.created_on }}</p>
                </div>
                <div class="card-body">
                    <article class="text-center fs-5">
                        <h2 class="d-none">Article title: {{ resource.title }}</h2>
                        {{ resource.content | safe}}
                    </article>
                    <div id="carouselResourceDetail{{ resource.id }}" class="carousel slide card-carousel">
                        {% if images %}
                        <div class="carousel-inner">
                            {% for media in resource.media.all %}
                            <div class="carousel-item {% if forloop.first %}active{% endif %}">
                                <div class="card-img-box">
                                    <img src="{{ media.featured_media.url }}" class="resource-image d-block"
                                        alt="Image for {{ resource.title }}">
                                </div>
                                <div class="media-download text-center">
                                    <a href="{{ media.featured_media.url }}" download="{{ media.featured_media.name }}"
                                        class="btn my-3" target="_blank">Download Media</a>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                        <button class="carousel-control-prev" type="button"
                            data-bs-target="#carouselResourceDetail{{ resource.id }}" data-bs-slide="prev">
                            <span class="carousel-control-prev-icon dark-bg" aria-hidden="true"></span>
                            <span class="visually-hidden">Previous</span>
                        </button>
                        <button class="carousel-control-next" type="button"
                            data-bs-target="#carouselResourceDetail{{ resource.id }}" data-bs-slide="next">
                            <span class="carousel-control-next-icon dark-bg" aria-hidden="true"></span>
                            <span class="visually-hidden">Next</span>
                        </button>
                        {% else %}
                        <div class="carousel-inner">
                            <div class="carousel-item active">
                                <div class="card-img-box">
                                    <img src="{% static 'images/bee-heart.png' %}" class="resource-image d-block" alt="cartoon bee">
                                </div>
                            </div>
                        </div>
                        {% endif %}
                    </div>
                </div>
                {% if resource.links %}
                <div class="card-footer">
                    <div class="row">
                        <div class="col col-12 text-truncate text-center details-link">
                            Link -
                            <a href="{{ resource.links }}" target="_blank"
                                aria-label="link to external website, opens in a new page">
                                {{ resource.links }}
                            </a>
                        </div>
                    </div>
                </div>
                {% endif %}
            </div>
        </div>
    </div>

    <div class="row  justify-content-center mb-5">
        <div class="col text-center">
            <a class="btn" href="{% url 'user_posts_list' %}">Back to My Resources</a>
        </div>
    </div>
</div>
{% endblock content %}

{% block script %}
<script src="{% static 'js/script.js' %}"></script>
{% endblock %}